"""Provider de test pour développement et tests unitaires.

Il permet d'exécuter le framework sans API externe.
"""

from __future__ import annotations

from typing import Any

from limen.providers.base import AIProvider


class MockProvider(AIProvider):
    """Provider déterministe basé sur des règles simples."""

    def __init__(self, name: str = "mock"):
        self.name = name

    def complete(
        self,
        system_prompt: str,
        user_prompt: str,
        *,
        temperature: float = 0.2,
        max_tokens: int | None = None,
        response_format: dict[str, Any] | None = None,
    ) -> str:
        del temperature, max_tokens, response_format

        if "Competence Assessor" in system_prompt:
            return (
                '{"confidence": 0.42, "risk": 0.63, '
                '"domain": "general", "complexity": "medium", '
                '"rationale": "Question non triviale, consultation utile."}'
            )

        if "Critic agent" in system_prompt:
            return (
                '{"summary": "Le brouillon est globalement utile mais incomplet.", '
                '"confirmed_errors": [], '
                '"likely_weaknesses": ["Manque de précision sur le contexte."], '
                '"suggested_fixes": ["Ajouter un exemple concret."], '
                '"severity_score": 6, '
                '"revision_useful": true}'
            )

        if "Synthesizer agent" in system_prompt:
            return (
                "Réponse finale synthétisée : le système recommande une consultation "
                "contrôlée puis une réponse consolidée."
            )

        return f"Draft generated by {self.name}: {user_prompt}"
